language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - python setup.py install
script:
  - coverage run setup.py test
after_success:
  - coveralls